version: '3.8'
secrets:
  hiot_db_password:
    external: true
  hiot_telegram_bot_token:
    external: true
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/hiot_db_password
      POSTGRES_DB: iot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hiot-internal  # Private network for internal communication
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - hiot_db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == null

  api:
    image: localhost:5000/hiot-api:latest
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=iot_db
      - TELEGRAM_CHAT_IDS=300492094,86537268
    networks:
      - hiot-internal     # Internal communication with db and telegram
      - traefik_traefik-network    # Use existing traefik network
    secrets:
      - hiot_db_password
      - hiot_telegram_bot_token
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=PathPrefix(`/hiot`)
        - traefik.http.routers.api.entrypoints=web
        - traefik.http.services.api.loadbalancer.server.port=8000
      placement:
        constraints:
          - node.hostname == null

  telegram-service:
    image: localhost:5000/hiot-telegram:latest
    environment:
      - API_URL=http://api:8000  # Use service name for internal communication
      - TELEGRAM_CHAT_IDS=300492094,86537268

    depends_on:
      - api
    networks:
      - hiot-internal  # Private network for internal communication
    secrets:
      - hiot_telegram_bot_token
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == null

volumes:
  postgres_data:

networks:
  hiot-internal:
    driver: overlay
    internal: true  # This makes it internal-only (no external internet access)
    attachable: true
  traefik_traefik-network:
    external: true  # Use the existing traefik network
